delete from loops;
insert into loops (name, url, number, category) values
	('Adriano', 'http://d1klj39g1g0ynu.cloudfront.net/videos/adriano/adriano', 19,'Vocals'),
	('Akila', 'http://d1klj39g1g0ynu.cloudfront.net/videos/akila/akila', 1,'Bass'),
	('Balu', 'http://d1klj39g1g0ynu.cloudfront.net/videos/balu/balu', 11,'Strings'),
	('Charlie', 'http://d1klj39g1g0ynu.cloudfront.net/videos/charlie/charlie', 2,'Vocals'),
	('Chantage', 'http://d1klj39g1g0ynu.cloudfront.net/videos/chantage/chantage', 12,'Percussion'),
	('Choir', 'http://d1klj39g1g0ynu.cloudfront.net/videos/choir/choir', 12,'Strings'),
	('Chris and Kate', 'http://d1klj39g1g0ynu.cloudfront.net/videos/chris-kate/chris-kate', 13,'Percussion'),
	('Hyelim', 'http://d1klj39g1g0ynu.cloudfront.net/videos/hyelim/hyelim', 14,''),
	('Jada', 'http://d1klj39g1g0ynu.cloudfront.net/videos/jada/jada', 3,'Percussion'),
	('Jason', 'http://d1klj39g1g0ynu.cloudfront.net/videos/jason/jason', 3,''),
	('Jorge', 'http://d1klj39g1g0ynu.cloudfront.net/videos/jorge/jorge', 15,'Percussion'),
	('Jo', 'http://d1klj39g1g0ynu.cloudfront.net/videos/jo/jo', 4,'Strings'),
	('JT', 'http://d1klj39g1g0ynu.cloudfront.net/videos/jt/jt', 5,'Drums'),
	('Kasper', 'http://d1klj39g1g0ynu.cloudfront.net/videos/kasper/kasper', 6,'Strings'),
	('Kath', 'http://d1klj39g1g0ynu.cloudfront.net/videos/kath/kath', 16,'Percussion'),
	('Lola', 'http://d1klj39g1g0ynu.cloudfront.net/videos/lola/lola', 7,'Percussion'),
	('Lola 2', 'http://d1klj39g1g0ynu.cloudfront.net/videos/lola2/lola2', 20,'Percussion'),
	('Sam', 'http://d1klj39g1g0ynu.cloudfront.net/videos/sam/sam', 8,'Vocals'),
	('Shaun', 'http://d1klj39g1g0ynu.cloudfront.net/videos/shaun/shaun', 17,'Rhythm'),
	('Raj', 'http://d1klj39g1g0ynu.cloudfront.net/videos/raj/raj', 18,'Drums'),
	('Tom', 'http://d1klj39g1g0ynu.cloudfront.net/videos/tom/tom', 9,'Rhythm'),
	('Zahara', 'http://d1klj39g1g0ynu.cloudfront.net/videos/zahara/zahara', 10, 'Rhythm');
